name: Auto Label

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: 'false'

      - name: Check core team membership
        id: check_team
        uses: ./.github/actions/check-core-team
        with:
          pr-author: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}

      - name: Apply triage label
        uses: actions/github-script@v7
        env:
          IS_INTERNAL: ${{ steps.check_team.outputs.is-internal }}
        with:
          script: |
            const issueNumber =
              context.payload.pull_request
                ? context.payload.pull_request.number
                : context.payload.issue.number;

            const triageLabel = process.env.IS_INTERNAL === 'true' ? 'internal' : 'needs triage';
            core.info(`Applying triage label: ${triageLabel}`);
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: [triageLabel],
            });
