name: Pull Request

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    uses: ./.github/workflows/ci-node.yml

  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    environment: development
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: 'false'

      - uses: ./.github/actions/setup-node-deps

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          buildScriptName: 'build:storybook'
          storybookBuildDir: 'storybook-static/'
          zip: true
          skip: "dependabot/**"
